name: Build APK for Android

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses6 libtinfo6 cmake libffi-dev libssl-dev build-essential

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36

      - name: Accept Android Licenses
        run: |
          mkdir -p \~/.buildozer/android/platform/android-sdk/licenses
          echo "8933bad161af4178b1185d1a37fcb7a0" > \~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > \~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

      - name: Build APK
        run: buildozer -v android debug
